// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRequest(arg1, arg2) {
  return window['go']['main']['App']['AddRequest'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['main']['App']['CreateEnvironment'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function GetActiveEnvironment() {
  return window['go']['main']['App']['GetActiveEnvironment']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportPostmanJSON(arg1) {
  return window['go']['main']['App']['ImportPostmanJSON'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function UpdateCollection(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2);
}

export function UpdateEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEnvironment'](arg1, arg2, arg3);
}

export function UpdateRequest(arg1, arg2) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2);
}
