// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRequest(arg1:string,arg2:main.RequestConfig):Promise<main.RequestConfig>;

export function ClearHistory():Promise<void>;

export function CreateCollection(arg1:string):Promise<main.Collection>;

export function CreateEnvironment(arg1:string):Promise<main.Environment>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteHistoryEntry(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string):Promise<void>;

export function GetActiveEnvironment():Promise<main.Environment>;

export function GetCollections():Promise<Array<main.Collection>>;

export function GetEnvironments():Promise<Array<main.Environment>>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function ImportPostmanJSON(arg1:string):Promise<main.ImportResult>;

export function SendRequest(arg1:main.RequestConfig):Promise<main.HTTPResponse>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function UpdateCollection(arg1:string,arg2:string):Promise<void>;

export function UpdateEnvironment(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function UpdateRequest(arg1:string,arg2:main.RequestConfig):Promise<void>;
